---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-catalog-management
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: tbc
    variations:
      - name: catalog
        mark_ready: true
        install_type: fullstack
      - name: vpe-object
        mark_ready: true
        install_type: fullstack
        pre_validation: "tests/scripts/pre-validate.sh"
        post_validation: "tests/scripts/post-validate.sh"
